apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reflections.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "reflections.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "reflections.fullname" . }}-backend
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: {{ include "reflections.backendImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "reflections.fullname" . }}-config
            - secretRef:
                name: {{ include "reflections.secretName" . }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
