{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "reflections.fullname" . }}-db-migrate
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    spec:
      restartPolicy: OnFailure
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: {{ include "reflections.backendImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npx", "prisma", "db", "push", "--force-reset"]
          envFrom:
            - secretRef:
                name: {{ include "reflections.secretName" . }}
            - configMapRef:
                name: {{ include "reflections.fullname" . }}-config
{{- end }}
