apiVersion: v1
kind: Service
metadata:
  name: {{ include "reflections.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ include "reflections.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
