{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "reflections.fullname" . }}-postgres-data
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  {{- if .Values.postgres.storage.storageClassName }}
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  {{- end }}
{{- end }}
